[package]
name = "ynab-swed"
version = "0.1.0"
authors = ["Karlis Lauva <karlis@karlis.me>"]
edition = "2018"

[dependencies]
clap = "2"
csv = "1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0.100", features = ["derive"] }
